apiVersion: v1
kind: Service

metadata:
  name: sample-backend

  labels:
    app: sample-backend

spec:
  selector:
    app: sample-backend

  ports:
    - name: http
      port: 8000
      targetPort: 8000